#!/usr/bin/env python

# A simple script that connects to a server and displays block headers

import time, electrum_pot as electrum

# 1. start the interface and wait for connection
interface = electrum.Interface('162.243.80.208:50001:t')
interface.start(wait = True)
if not interface.is_connected:
    print "not connected"
    exit()

# 2. send the subscription
callback = lambda _,result: electrum.print_json(result.get('result'))
interface.send([('blockchain.headers.subscribe',[])], callback)

# 3. wait for results
while interface.is_connected:
    time.sleep(1)
